USE [master]
GO
/****** Object:  Database [PersonasyUsuarios]    Script Date: 12/12/2024 21:33:11 ******/
CREATE DATABASE [PersonasyUsuarios]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PersonasyUsuarios', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PersonasyUsuarios.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PersonasyUsuarios_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PersonasyUsuarios_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [PersonasyUsuarios] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PersonasyUsuarios].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PersonasyUsuarios] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET ARITHABORT OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PersonasyUsuarios] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PersonasyUsuarios] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PersonasyUsuarios] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PersonasyUsuarios] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PersonasyUsuarios] SET  MULTI_USER 
GO
ALTER DATABASE [PersonasyUsuarios] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PersonasyUsuarios] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PersonasyUsuarios] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PersonasyUsuarios] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PersonasyUsuarios] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PersonasyUsuarios] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PersonasyUsuarios] SET QUERY_STORE = ON
GO
ALTER DATABASE [PersonasyUsuarios] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [PersonasyUsuarios]
GO
/****** Object:  Table [dbo].[Personas]    Script Date: 12/12/2024 21:33:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Personas](
	[Id_Personas] [int] IDENTITY(1,1) NOT NULL,
	[Nombres] [varchar](50) NULL,
	[Apellidos] [varchar](50) NULL,
	[Num_Identificacion] [varchar](50) NULL,
	[Email] [varchar](50) NULL,
	[Tipo_identificacion] [varchar](50) NULL,
	[Fecha_creacion] [datetime] NULL,
 CONSTRAINT [PK_Personas] PRIMARY KEY CLUSTERED 
(
	[Id_Personas] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 12/12/2024 21:33:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[Id_Usuarios] [int] IDENTITY(1,1) NOT NULL,
	[Usuario] [varchar](50) NULL,
	[Contraseña] [varchar](64) NULL,
	[Fecha_creacion] [datetime] NULL,
	[HashKey] [binary](32) NULL,
	[HashIV] [binary](16) NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[Id_Usuarios] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [PersonasyUsuarios] SET  READ_WRITE 
GO
